version: "3.9"
services:
  backend:
    build: ./backend
    container_name: multitools-backend
    ports:
      - "8000:8000"
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: multitools-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app.py:/app/streamlit_app.py
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
