[build]
builder = "nixpacks"

[deploy]
startCommand = "streamlit run streamlit_app.py --server.port=$PORT --server.address=0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PYTHON_VERSION = "3.11"
STREAMLIT_SERVER_PORT = "$PORT"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
